//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinrarKG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinrarKG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational purposes only. No ads, no music, no bullshit..
        /// </summary>
        internal static string about_hdr_desc {
            get {
                return ResourceManager.GetString("about_hdr_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPG KeyID.
        /// </summary>
        internal static string about_lbl_gpg {
            get {
                return ResourceManager.GetString("about_lbl_gpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signature Thumbprint.
        /// </summary>
        internal static string about_lbl_thumbprint {
            get {
                return ResourceManager.GetString("about_lbl_thumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Repo.
        /// </summary>
        internal static string about_lnk_github {
            get {
                return ResourceManager.GetString("about_lnk_github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPB Profile.
        /// </summary>
        internal static string about_lnk_tpb {
            get {
                return ResourceManager.GetString("about_lnk_tpb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Generate.
        /// </summary>
        internal static string btn_generate {
            get {
                return ResourceManager.GetString("btn_generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string btn_generate_copy {
            get {
                return ResourceManager.GetString("btn_generate_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Keyfile.
        /// </summary>
        internal static string btn_savekeyfile {
            get {
                return ResourceManager.GetString("btn_savekeyfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chat {
            get {
                object obj = ResourceManager.GetObject("chat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save WinRAR License Key.
        /// </summary>
        internal static string dlg_save_title {
            get {
                return ResourceManager.GetString("dlg_save_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exclamation {
            get {
                object obj = ResourceManager.GetObject("exclamation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated License Key.
        /// </summary>
        internal static string lbl_generate_license {
            get {
                return ResourceManager.GetString("lbl_generate_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lbl_generate_name {
            get {
                return ResourceManager.GetString("lbl_generate_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate a required library file:{0}{1}{2}{3}Add the missing library file and restart the program..
        /// </summary>
        internal static string msgbox_err_libmissing_msg {
            get {
                return ResourceManager.GetString("msgbox_err_libmissing_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        internal static string msgbox_err_libmissing_title {
            get {
                return ResourceManager.GetString("msgbox_err_libmissing_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save an empty WinRAR keyfile.
        ///
        ///Enter a valid name &amp; company / license name; then click &quot;Generate&quot;.
        /// </summary>
        internal static string msgbox_licempty_msg {
            get {
                return ResourceManager.GetString("msgbox_licempty_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Generated Response.
        /// </summary>
        internal static string msgbox_licempty_title {
            get {
                return ResourceManager.GetString("msgbox_licempty_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keygen cannot determine where WinRAR is installed.
        ///
        ///Copy the generated key and place it inside a file labeled rarreg.key.
        ///
        ///Then place the file in your WinRAR folder..
        /// </summary>
        internal static string msgbox_nolocnopath_msg {
            get {
                return ResourceManager.GetString("msgbox_nolocnopath_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Find WinRAR.
        /// </summary>
        internal static string msgbox_nolocnopath_title {
            get {
                return ResourceManager.GetString("msgbox_nolocnopath_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keygen cannot determine where WinRAR is installed
        ///Tried looking in {0}.
        ///
        ///Copy the generated key and place it inside a file labeled rarreg.key
        ///
        ///Then place the file in your WinRAR folder..
        /// </summary>
        internal static string msgbox_nolocpath_msg {
            get {
                return ResourceManager.GetString("msgbox_nolocpath_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Locate WinRAR.
        /// </summary>
        internal static string msgbox_nolocpath_title {
            get {
                return ResourceManager.GetString("msgbox_nolocpath_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a name before you attempt to generate a license key.
        /// </summary>
        internal static string msgbox_noname_msg {
            get {
                return ResourceManager.GetString("msgbox_noname_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name specified.
        /// </summary>
        internal static string msgbox_noname_title {
            get {
                return ResourceManager.GetString("msgbox_noname_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved rarreg.key.\nRestart WinRAR for license to apply..
        /// </summary>
        internal static string msgbox_save_msg {
            get {
                return ResourceManager.GetString("msgbox_save_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keygen Installed Successfully.
        /// </summary>
        internal static string msgbox_save_title {
            get {
                return ResourceManager.GetString("msgbox_save_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Generate to create license key ....
        /// </summary>
        internal static string statusbar_generate {
            get {
                return ResourceManager.GetString("statusbar_generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate license key first.
        /// </summary>
        internal static string statusbar_generate_first {
            get {
                return ResourceManager.GetString("statusbar_generate_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License key generated. Paste into WinRAR directory..
        /// </summary>
        internal static string statusbar_generated {
            get {
                return ResourceManager.GetString("statusbar_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error: Can&apos;t find {0}.
        /// </summary>
        internal static string statusbar_libmissing {
            get {
                return ResourceManager.GetString("statusbar_libmissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License key copied. Paste into rarreg.key.
        /// </summary>
        internal static string statusbar_license_copied {
            get {
                return ResourceManager.GetString("statusbar_license_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved license key to {0}.
        /// </summary>
        internal static string statusbar_license_saved {
            get {
                return ResourceManager.GetString("statusbar_license_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        internal static string template_btn_abort {
            get {
                return ResourceManager.GetString("template_btn_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string template_btn_cancel {
            get {
                return ResourceManager.GetString("template_btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignore.
        /// </summary>
        internal static string template_btn_ignore {
            get {
                return ResourceManager.GetString("template_btn_ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        internal static string template_btn_no {
            get {
                return ResourceManager.GetString("template_btn_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string template_btn_ok {
            get {
                return ResourceManager.GetString("template_btn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retry.
        /// </summary>
        internal static string template_btn_retry {
            get {
                return ResourceManager.GetString("template_btn_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        internal static string template_btn_yes {
            get {
                return ResourceManager.GetString("template_btn_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] winrarkg_cli {
            get {
                object obj = ResourceManager.GetObject("winrarkg_cli", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
