//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinrarKG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinrarKG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational purposes only. No ads, no music, no bullshit..
        /// </summary>
        internal static string about_hdr_desc {
            get {
                return ResourceManager.GetString("about_hdr_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPG KeyID.
        /// </summary>
        internal static string about_lbl_gpg {
            get {
                return ResourceManager.GetString("about_lbl_gpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signature Thumbprint.
        /// </summary>
        internal static string about_lbl_thumbprint {
            get {
                return ResourceManager.GetString("about_lbl_thumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Repo.
        /// </summary>
        internal static string about_lnk_github {
            get {
                return ResourceManager.GetString("about_lnk_github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPB Profile.
        /// </summary>
        internal static string about_lnk_tpb {
            get {
                return ResourceManager.GetString("about_lnk_tpb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bch {
            get {
                object obj = ResourceManager.GetObject("bch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_header {
            get {
                object obj = ResourceManager.GetObject("bg_header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btc {
            get {
                object obj = ResourceManager.GetObject("btc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Generate.
        /// </summary>
        internal static string btn_generate {
            get {
                return ResourceManager.GetString("btn_generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string btn_generate_copy {
            get {
                return ResourceManager.GetString("btn_generate_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Keyfile.
        /// </summary>
        internal static string btn_savekeyfile {
            get {
                return ResourceManager.GetString("btn_savekeyfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        internal static string btn_template_abort {
            get {
                return ResourceManager.GetString("btn_template_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string btn_template_cancel {
            get {
                return ResourceManager.GetString("btn_template_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignore.
        /// </summary>
        internal static string btn_template_ignore {
            get {
                return ResourceManager.GetString("btn_template_ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        internal static string btn_template_no {
            get {
                return ResourceManager.GetString("btn_template_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string btn_template_ok {
            get {
                return ResourceManager.GetString("btn_template_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retry.
        /// </summary>
        internal static string btn_template_retry {
            get {
                return ResourceManager.GetString("btn_template_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        internal static string btn_template_yes {
            get {
                return ResourceManager.GetString("btn_template_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chat {
            get {
                object obj = ResourceManager.GetObject("chat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save WinRAR License Key.
        /// </summary>
        internal static string dlg_save_title {
            get {
                return ResourceManager.GetString("dlg_save_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eth {
            get {
                object obj = ResourceManager.GetObject("eth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exclamation {
            get {
                object obj = ResourceManager.GetObject("exclamation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCH.
        /// </summary>
        internal static string lbl_contrib_bch {
            get {
                return ResourceManager.GetString("lbl_contrib_bch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTC.
        /// </summary>
        internal static string lbl_contrib_btc {
            get {
                return ResourceManager.GetString("lbl_contrib_btc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETH.
        /// </summary>
        internal static string lbl_contrib_eth {
            get {
                return ResourceManager.GetString("lbl_contrib_eth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated License Key.
        /// </summary>
        internal static string lbl_generate_license {
            get {
                return ResourceManager.GetString("lbl_generate_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lbl_generate_name {
            get {
                return ResourceManager.GetString("lbl_generate_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program requires it being ran as admin. Right-click on the program and select &quot;Run As Admin&quot;..
        /// </summary>
        internal static string msgbox_core_runas_msg {
            get {
                return ResourceManager.GetString("msgbox_core_runas_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Admin.
        /// </summary>
        internal static string msgbox_core_runas_title {
            get {
                return ResourceManager.GetString("msgbox_core_runas_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string msgbox_debug_callfunc_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_callfunc_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Called.
        /// </summary>
        internal static string msgbox_debug_callfunc_title {
            get {
                return ResourceManager.GetString("msgbox_debug_callfunc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to disable debug logging?.
        /// </summary>
        internal static string msgbox_debug_egg_disable_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_egg_disable_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Debug Logging?.
        /// </summary>
        internal static string msgbox_debug_egg_disable_title {
            get {
                return ResourceManager.GetString("msgbox_debug_egg_disable_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to enable debug logging?
        ///
        ///All logs will be stored in the location:
        ///     {0}.
        /// </summary>
        internal static string msgbox_debug_egg_enable_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_egg_enable_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Debug Logging?.
        /// </summary>
        internal static string msgbox_debug_egg_enable_title {
            get {
                return ResourceManager.GetString("msgbox_debug_egg_enable_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located {0} with Windows Env Var in:
        ///
        ///{1}.
        /// </summary>
        internal static string msgbox_debug_fpath_env_c1_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_env_c1_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: 1000C-1.
        /// </summary>
        internal static string msgbox_debug_fpath_env_c1_title {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_env_c1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located {0} with Windows Env Var in:
        ///
        ///{1}.
        /// </summary>
        internal static string msgbox_debug_fpath_env_c2_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_env_c2_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: 1000C-2.
        /// </summary>
        internal static string msgbox_debug_fpath_env_c2_title {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_env_c2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located {0} In:
        ///
        ///{1}.
        /// </summary>
        internal static string msgbox_debug_fpath_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located {0} with Powershell in:
        ///
        ///{1}.
        /// </summary>
        internal static string msgbox_debug_fpath_ps_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_ps_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: 1000B.
        /// </summary>
        internal static string msgbox_debug_fpath_ps_title {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_ps_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: 1000A.
        /// </summary>
        internal static string msgbox_debug_fpath_title {
            get {
                return ResourceManager.GetString("msgbox_debug_fpath_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string msgbox_debug_ps_output_msg {
            get {
                return ResourceManager.GetString("msgbox_debug_ps_output_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: PowerShell Output.
        /// </summary>
        internal static string msgbox_debug_ps_output_title {
            get {
                return ResourceManager.GetString("msgbox_debug_ps_output_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate a required library file:{0}{1}{2}{3}Add the missing library file and restart the program..
        /// </summary>
        internal static string msgbox_err_libmissing_msg {
            get {
                return ResourceManager.GetString("msgbox_err_libmissing_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        internal static string msgbox_err_libmissing_title {
            get {
                return ResourceManager.GetString("msgbox_err_libmissing_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate {0}. Try placing the keygen file {1} in the same folder as the {0} program executable.
        ///
        ///The next dialog will allow you to simply save the license file {2}
        ///
        ///You&apos;ll need to copy/paste the saved {2} file into the WinRAR installation folder..
        /// </summary>
        internal static string msgbox_err_locate_msg {
            get {
                return ResourceManager.GetString("msgbox_err_locate_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid Path to {0}.
        /// </summary>
        internal static string msgbox_err_locate_title {
            get {
                return ResourceManager.GetString("msgbox_err_locate_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate a required library file:
        ///   {0}
        ///
        ///Add the missing library file and restart the program..
        /// </summary>
        internal static string msgbox_err_misslib_msg {
            get {
                return ResourceManager.GetString("msgbox_err_misslib_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        internal static string msgbox_err_misslib_title {
            get {
                return ResourceManager.GetString("msgbox_err_misslib_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License generation has been cancelled..
        /// </summary>
        internal static string msgbox_generate_cancel_msg {
            get {
                return ResourceManager.GetString("msgbox_generate_cancel_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Cancelled.
        /// </summary>
        internal static string msgbox_generate_cancel_title {
            get {
                return ResourceManager.GetString("msgbox_generate_cancel_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save an empty WinRAR keyfile.
        ///
        ///Enter a valid name &amp; company / license name; then click &quot;Generate&quot;.
        /// </summary>
        internal static string msgbox_licempty_msg {
            get {
                return ResourceManager.GetString("msgbox_licempty_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Generated Response.
        /// </summary>
        internal static string msgbox_licempty_title {
            get {
                return ResourceManager.GetString("msgbox_licempty_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0}, so I can&apos;t open the folder.
        ///
        ///You will now be asked to manually select a location to save the generated license key file.
        ///
        ///The following locations were searched:
        ///{1}.
        /// </summary>
        internal static string msgbox_nolocate_cannot_open_msg {
            get {
                return ResourceManager.GetString("msgbox_nolocate_cannot_open_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Not Found.
        /// </summary>
        internal static string msgbox_nolocate_cannot_open_title {
            get {
                return ResourceManager.GetString("msgbox_nolocate_cannot_open_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keygen cannot determine where WinRAR is installed.
        ///
        ///Copy the generated key and place it inside a file labeled rarreg.key.
        ///
        ///Then place the file in your WinRAR folder..
        /// </summary>
        internal static string msgbox_nolocnopath_msg {
            get {
                return ResourceManager.GetString("msgbox_nolocnopath_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Find WinRAR.
        /// </summary>
        internal static string msgbox_nolocnopath_title {
            get {
                return ResourceManager.GetString("msgbox_nolocnopath_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keygen cannot determine where WinRAR is installed
        ///Tried looking in {0}.
        ///
        ///Copy the generated key and place it inside a file labeled rarreg.key
        ///
        ///Then place the file in your WinRAR folder..
        /// </summary>
        internal static string msgbox_nolocpath_msg {
            get {
                return ResourceManager.GetString("msgbox_nolocpath_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Locate WinRAR.
        /// </summary>
        internal static string msgbox_nolocpath_title {
            get {
                return ResourceManager.GetString("msgbox_nolocpath_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a name before you attempt to generate a license key.
        /// </summary>
        internal static string msgbox_noname_msg {
            get {
                return ResourceManager.GetString("msgbox_noname_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name specified.
        /// </summary>
        internal static string msgbox_noname_title {
            get {
                return ResourceManager.GetString("msgbox_noname_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License key has been successfully generated in:
        ///
        ///{0}.
        /// </summary>
        internal static string msgbox_ok_generate_finished_msg {
            get {
                return ResourceManager.GetString("msgbox_ok_generate_finished_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Key Generated.
        /// </summary>
        internal static string msgbox_ok_generate_finished_title {
            get {
                return ResourceManager.GetString("msgbox_ok_generate_finished_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to generate a new license key for WinRAR?.
        /// </summary>
        internal static string msgbox_ok_generate_msg {
            get {
                return ResourceManager.GetString("msgbox_ok_generate_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved rarreg.key to the following location:
        ///     {0}
        ///
        ///Restart WinRAR for license to apply..
        /// </summary>
        internal static string msgbox_save_msg {
            get {
                return ResourceManager.GetString("msgbox_save_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keygen Installed Successfully.
        /// </summary>
        internal static string msgbox_save_title {
            get {
                return ResourceManager.GetString("msgbox_save_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update v{0} is available.
        ///
        ///Updates ensure this patch works with the latest version {1}. If you have issues using this tool, download the latest version in the top menu: Help ► Updates
        ///
        ///Would you like to view the update? If not, program will start as normal..
        /// </summary>
        internal static string msgbox_update_msg {
            get {
                return ResourceManager.GetString("msgbox_update_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available: {0} ► {1}.
        /// </summary>
        internal static string msgbox_update_title {
            get {
                return ResourceManager.GetString("msgbox_update_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notify_01 {
            get {
                object obj = ResourceManager.GetObject("notify_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License generated..
        /// </summary>
        internal static string status_action_generated {
            get {
                return ResourceManager.GetString("status_action_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to copy generated key to clipboard.
        /// </summary>
        internal static string status_btn_copy_mo {
            get {
                return ResourceManager.GetString("status_btn_copy_mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the folder where {0} is installed.
        /// </summary>
        internal static string status_btn_openfolder {
            get {
                return ResourceManager.GetString("status_btn_openfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save generated key to file rarreg.key.
        /// </summary>
        internal static string status_btn_save_mo {
            get {
                return ResourceManager.GetString("status_btn_save_mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key generation cancelled by user.
        /// </summary>
        internal static string status_diag_cancelled {
            get {
                return ResourceManager.GetString("status_diag_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Generate to create license key ....
        /// </summary>
        internal static string status_genlicense {
            get {
                return ResourceManager.GetString("status_genlicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error -- restart keygen.
        /// </summary>
        internal static string status_misslib_critical_fail {
            get {
                return ResourceManager.GetString("status_misslib_critical_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Generate to create license key ....
        /// </summary>
        internal static string statusbar_generate {
            get {
                return ResourceManager.GetString("statusbar_generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate license key first.
        /// </summary>
        internal static string statusbar_generate_first {
            get {
                return ResourceManager.GetString("statusbar_generate_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License key generated. Paste into WinRAR directory..
        /// </summary>
        internal static string statusbar_generated {
            get {
                return ResourceManager.GetString("statusbar_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error: Can&apos;t find {0}.
        /// </summary>
        internal static string statusbar_libmissing {
            get {
                return ResourceManager.GetString("statusbar_libmissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License key copied. Paste into rarreg.key.
        /// </summary>
        internal static string statusbar_license_copied {
            get {
                return ResourceManager.GetString("statusbar_license_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved license key to {0}.
        /// </summary>
        internal static string statusbar_license_saved {
            get {
                return ResourceManager.GetString("statusbar_license_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do this because I enjoy giving back, and I&apos;m not looking to make a profit off my work. However, donations would help immensely for one purpose -- purchasing libraries and other commercial products which have insane licensing systems. These types of products would make life much easier and get releases pumped out on a more regular basis. Don&apos;t feel obligated, this is just &quot;if you can&quot;. My main goal is better tools..
        /// </summary>
        internal static string txt_contrib_intro {
            get {
                return ResourceManager.GetString("txt_contrib_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] winrarkg_cli {
            get {
                object obj = ResourceManager.GetObject("winrarkg_cli", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
